project_id = "eddduafponbimicjownw"

[functions.create-payment]
verify_jwt = false

[functions.manage-installments]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false

[functions.log-payment]
verify_jwt = false

[functions.track-checkout-event]
verify_jwt = false

[functions.get-conversion-analytics]
verify_jwt = false